version: '3'
services:
  spark-master:
    image: bde2020/spark-master:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==master"
  spark-worker:
    image: bde2020/spark-worker:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==worker"
